const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareWidth
	];
};
self.C3_JsPropNameTable = [
	{durum: 0},
	{position1: 0},
	{position10: 0},
	{position11: 0},
	{position12: 0},
	{position13: 0},
	{position14: 0},
	{position15: 0},
	{position16: 0},
	{position2: 0},
	{position3: 0},
	{position4: 0},
	{position5: 0},
	{position6: 0},
	{position7: 0},
	{position8: 0},
	{position9: 0},
	{position17: 0},
	{position18: 0},
	{position19: 0},
	{position20: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{kapak: 0},
	{Sine: 0},
	{btn_play: 0},
	{btn_info: 0},
	{btn_emgecen: 0},
	{btn_kaynakca: 0},
	{btn_home: 0},
	{btn_ekranboyut: 0},
	{btn_sesac: 0},
	{btn_seskapat: 0},
	{oyun_arkplan: 0},
	{tebrik_arkplan: 0},
	{btn_tekraroyna: 0},
	{soru_cerceve: 0},
	{Tween: 0},
	{info: 0},
	{meb_logo: 0},
	{sure_halka: 0},
	{tik: 0},
	{tabrikcerceve: 0},
	{wrong: 0},
	{Browser: 0},
	{ecowordsgame: 0},
	{puan_serit: 0},
	{sure_serit: 0},
	{puandaire: 0},
	{Flash: 0},
	{puanyildiz: 0},
	{Text: 0},
	{test: 0},
	{compost: 0},
	{balanced_diet: 0},
	{crops: 0},
	{processedmeat: 0},
	{fibrerich: 0},
	{fake1: 0},
	{fake2: 0},
	{fake3: 0},
	{fake4: 0},
	{fake5: 0},
	{test2: 0},
	{crops2: 0},
	{compost2: 0},
	{inspire: 0},
	{unity: 0},
	{culturelexchange: 0},
	{test3: 0},
	{balanced_diet2: 0},
	{processedmeat2: 0},
	{culturelexchange2: 0},
	{representative: 0},
	{inspire2: 0},
	{test4: 0},
	{crops3: 0},
	{fibrerich2: 0},
	{unity2: 0},
	{representative2: 0},
	{inspire3: 0},
	{kupa: 0},
	{congratula: 0},
	{Particles: 0},
	{sure_akan: 0},
	{btns: 0},
	{hand: 0},
	{DragDrop: 0},
	{cevaplar: 0},
	{positions: 0},
	{infopage: 0},
	{sure_deg: 0},
	{dogrusayisi: 0},
	{yanlissayisi: 0},
	{posX: 0},
	{posY: 0},
	{puan: 0},
	{sayac: 0}
];

self.InstanceType = {
	position1: class extends self.ISpriteInstance {},
	position10: class extends self.ISpriteInstance {},
	position11: class extends self.ISpriteInstance {},
	position12: class extends self.ISpriteInstance {},
	position13: class extends self.ISpriteInstance {},
	position14: class extends self.ISpriteInstance {},
	position15: class extends self.ISpriteInstance {},
	position16: class extends self.ISpriteInstance {},
	position2: class extends self.ISpriteInstance {},
	position3: class extends self.ISpriteInstance {},
	position4: class extends self.ISpriteInstance {},
	position5: class extends self.ISpriteInstance {},
	position6: class extends self.ISpriteInstance {},
	position7: class extends self.ISpriteInstance {},
	position8: class extends self.ISpriteInstance {},
	position9: class extends self.ISpriteInstance {},
	position17: class extends self.ISpriteInstance {},
	position18: class extends self.ISpriteInstance {},
	position19: class extends self.ISpriteInstance {},
	position20: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	kapak: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_emgecen: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_ekranboyut: class extends self.ISpriteInstance {},
	btn_sesac: class extends self.ISpriteInstance {},
	btn_seskapat: class extends self.ISpriteInstance {},
	oyun_arkplan: class extends self.ISpriteInstance {},
	tebrik_arkplan: class extends self.ISpriteInstance {},
	btn_tekraroyna: class extends self.ISpriteInstance {},
	soru_cerceve: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	meb_logo: class extends self.ISpriteInstance {},
	sure_halka: class extends self.ISpriteInstance {},
	tik: class extends self.ISpriteInstance {},
	tabrikcerceve: class extends self.ISpriteInstance {},
	wrong: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	ecowordsgame: class extends self.ISpriteInstance {},
	puan_serit: class extends self.ISpriteInstance {},
	sure_serit: class extends self.ISpriteInstance {},
	puandaire: class extends self.ISpriteInstance {},
	puanyildiz: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	test: class extends self.ISpriteInstance {},
	compost: class extends self.ISpriteInstance {},
	balanced_diet: class extends self.ISpriteInstance {},
	crops: class extends self.ISpriteInstance {},
	processedmeat: class extends self.ISpriteInstance {},
	fibrerich: class extends self.ISpriteInstance {},
	fake1: class extends self.ISpriteInstance {},
	fake2: class extends self.ISpriteInstance {},
	fake3: class extends self.ISpriteInstance {},
	fake4: class extends self.ISpriteInstance {},
	fake5: class extends self.ISpriteInstance {},
	test2: class extends self.ISpriteInstance {},
	crops2: class extends self.ISpriteInstance {},
	compost2: class extends self.ISpriteInstance {},
	inspire: class extends self.ISpriteInstance {},
	unity: class extends self.ISpriteInstance {},
	culturelexchange: class extends self.ISpriteInstance {},
	test3: class extends self.ISpriteInstance {},
	balanced_diet2: class extends self.ISpriteInstance {},
	processedmeat2: class extends self.ISpriteInstance {},
	culturelexchange2: class extends self.ISpriteInstance {},
	representative: class extends self.ISpriteInstance {},
	inspire2: class extends self.ISpriteInstance {},
	test4: class extends self.ISpriteInstance {},
	crops3: class extends self.ISpriteInstance {},
	fibrerich2: class extends self.ISpriteInstance {},
	unity2: class extends self.ISpriteInstance {},
	representative2: class extends self.ISpriteInstance {},
	inspire3: class extends self.ISpriteInstance {},
	kupa: class extends self.ISpriteInstance {},
	congratula: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	sure_akan: class extends self.ISpriteInstance {},
	btns: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	cevaplar: class extends self.ISpriteInstance {},
	positions: class extends self.ISpriteInstance {}
}